### PR TITLE
added accordion to team

### PR DESCRIPTION
**Pull request by ssuds**
Made team members collapsible by year, to match the formatting of "cars" page

### CODE REVIEW

**Comment by mass** [comment]
On the cars page, when you click a tab only that tab will open and all the others will close. That isn't happening here, and I think it's a good idea to keep everything consistent

**Comment by ssuds** [comment]
Should be easy enough to fix, I'll get on that.

**Comment by ssuds** [comment]
Just double checked, and the "only one panel open at a time" behavior is happening on both pages for me. Try it again? I don't see any differences in the code that would cause them to behave any differently...

**Comment by mass** [comment]
It's not working for me. Also, the first box has some weird formatting/styling that the other two dont

**Comment by ssuds** [comment]
Fixed the weird formatting. Still not able to replicate the issue with tabs not collapsing automatically. Tried a few different browsers and have the same behavior everywhere. Maybe try after this latest commit?

**Comment by ssuds** [comment]
bump

**Comment by mass** [comment]
There's still some weird formatting things going on, as can be seen in this picture (no spacing): screenshot from 2016-02-12 13-04-37

Also, when you click the next year to open it, your scroll winds up at the bottom of that new year. Which is kind not user friendly. It should be easy to write some javascript to manually scroll the page to the "correct" place when a user clicks a new year.

**Comment by mass** [comment]
@ssuds, should we figure that one bug out and merge this in?

**Comment by ssuds** [comment]
Yeah. will need to pull in changes that were made since then but should be simple enough.

**Comment by ssuds** [comment]
It looks like f12e8e325a10f11939d63ef11a4458336fafb9c2 works this in

**Pull request closed without merging**
