### PR TITLE
updated main photo to 2015 car and recolored logo

### PR DESCRIPTION
**Pull request by ssuds**
I think this combo of logo and photo looks good

### CODE REVIEW

**Comment by mass** [comment]
I dont know, it's really hard for me to read the white. I don't like it that much. Also, that photo seems kind of low res or blurry. Like it was made blurry but not enough. Idk it just looks weird

**Comment by ssuds** [comment]
I can blur the photo further and see how that looks. With no blur it's unreadable regardless of color. I tried orange, black and white and white seemed the best. We could do a black and white photo again I suppose but that was pretty universally not that well recieved

**Comment by ssuds** [comment]
Bump, I can blur this more if you want but at least this change would have a current car photo instead of a 3 year old b&w photo

**Comment by mass** [comment]
Let's finalize the design before we worry about changing it

**Pull request closed without merging**
